# Generated by Django 4.2.15 on 2024-08-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.IntegerField(verbose_name="цена(в копейках)"),
        ),
    ]
