# Generated by Django 4.2.15 on 2024-08-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_item_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="цена"
            ),
        ),
    ]
