# Generated by Django 4.2.15 on 2024-08-31 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0004_alter_item_name"),
        ("order", "0002_orderitemm2m_order_items"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitemm2m",
            options={
                "verbose_name": "товар заказа",
                "verbose_name_plural": "товары заказа",
            },
        ),
        migrations.AlterUniqueTogether(
            name="orderitemm2m",
            unique_together={("order", "item")},
        ),
    ]
