# Generated by Django 4.2.15 on 2024-08-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_discount_tax_order_discount_order_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="stripe_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="stripe_id"
            ),
        ),
        migrations.AddField(
            model_name="tax",
            name="stripe_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="stripe_id"
            ),
        ),
    ]
