# Generated by Django 4.2.15 on 2024-08-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_discount_stripe_id_tax_stripe_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="stripe_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="stripe_id",
            ),
        ),
        migrations.AlterField(
            model_name="tax",
            name="stripe_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="stripe_id",
            ),
        ),
    ]
